import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo } from "./(components)/Navbar";
import Mainnav from "./(components)/Mainnav";
import FlecheRemonte from "./(components)/FlecheRemonte";
import Footer from "./(components)/Footer";
import BarreLecture from "./(components)/BarreLecture";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#08262E] flex flex-col-reverse">
          <Footer />
          <FlecheRemonte />

          {children}
          <Mainnav />
          <BarreLecture/>
        </div>
      </body>
    </html>
  );
}
